/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceJAVA;

import javax.swing.JFrame;
import InterfaceJAVA.tuan1;
import InterfaceJAVA.tuan2;
import InterfaceJAVA.tuan3;
/**
 *
 * @author Manh VU
 */
public class MyInterface extends javax.swing.JFrame {

    /**
     * Creates new form MyInterface
     */
    public MyInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btTuan1 = new javax.swing.JButton();
        btTuan2 = new javax.swing.JButton();
        btTuan3 = new javax.swing.JButton();
        DHBK = new javax.swing.JLabel();
        projectI = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vũ Duy Mạnh - 20162679");
        setBackground(new java.awt.Color(255, 255, 51));
        setFont(new java.awt.Font("Agency FB", 2, 10)); // NOI18N

        btTuan1.setBackground(new java.awt.Color(51, 51, 255));
        btTuan1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btTuan1.setForeground(new java.awt.Color(255, 255, 255));
        btTuan1.setText("Bài tập JAVA tuần 1");
        btTuan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTuan1ActionPerformed(evt);
            }
        });

        btTuan2.setBackground(new java.awt.Color(51, 51, 255));
        btTuan2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btTuan2.setForeground(new java.awt.Color(255, 255, 255));
        btTuan2.setText("Bài tập JAVA tuần 2");
        btTuan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTuan2ActionPerformed(evt);
            }
        });

        btTuan3.setBackground(new java.awt.Color(51, 51, 255));
        btTuan3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btTuan3.setForeground(new java.awt.Color(255, 255, 255));
        btTuan3.setText("Bài tập JAVA tuần 3");
        btTuan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTuan3ActionPerformed(evt);
            }
        });

        DHBK.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        DHBK.setForeground(new java.awt.Color(255, 0, 51));
        DHBK.setText("ĐẠI HỌC BÁCH KHOA HÀ NỘI");
        DHBK.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                DHBKAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        projectI.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        projectI.setForeground(new java.awt.Color(255, 51, 51));
        projectI.setText("PROJECT 1");

        jLabel1.setFont(new java.awt.Font("Calibri Light", 2, 18)); // NOI18N
        jLabel1.setText("GVHD: Ths. Lê Thị Hoa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(DHBK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(projectI)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btTuan1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addComponent(btTuan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btTuan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DHBK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectI, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(btTuan1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btTuan2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btTuan3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTuan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTuan1ActionPerformed
        tuan1 t1=new tuan1();
        t1.setVisible(true);
        t1.setLocation(600, 100);
        t1.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        t1.setResizable(false);
    }//GEN-LAST:event_btTuan1ActionPerformed

    private void btTuan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTuan3ActionPerformed
        tuan3 t3=new tuan3();
        t3.setVisible(true);
        t3.setLocation(600, 100);
        t3.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        t3.setResizable(false);
    }//GEN-LAST:event_btTuan3ActionPerformed

    private void DHBKAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_DHBKAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_DHBKAncestorAdded

    private void btTuan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTuan2ActionPerformed
        tuan2 t2=new tuan2();
        t2.setVisible(true);
        t2.setLocation(600, 100);
        t2.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        t2.setResizable(false);
    }//GEN-LAST:event_btTuan2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MyInterface giaodien=new MyInterface();
                giaodien.setVisible(true);
                giaodien.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                giaodien.setResizable(false);
           
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DHBK;
    private javax.swing.JButton btTuan1;
    private javax.swing.JButton btTuan2;
    private javax.swing.JButton btTuan3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel projectI;
    // End of variables declaration//GEN-END:variables
}
